version: "3.8"


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
#    command: uwsgi --ini config/uwsgi.ini
    command: gunicorn educa.wsgi:application --bind 0.0.0.0:8000
    volumes:
#      - ./:/usr/src/educa/
      - static_volume:/usr/src/educa/staticfiles
      - media_volume:/usr/src/educa/media
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
    depends_on:
      - db
      - cache

  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=educa

  cache:
#    image: memcached:1.6.10-alpine
    image: redis:6-alpine

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/educa/staticfiles
      - media_volume:/usr/src/educa/media
    ports:
      - 80:8000
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
  media_volume:
