version: "3.8"


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/educa/
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.dev
    depends_on:
      - db
      - cache

  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=educa
    ports:
      - 5432:5432

  cache:
#    image: memcached:1.6.10-alpine
    image: redis:6-alpine

volumes:
  postgres_data:
