FROM python:3.9-slim

ENV APP_HOME=/usr/src/educa
WORKDIR $APP_HOME

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir $APP_HOME/staticfiles
RUN mkdir $APP_HOME/media

RUN apt-get update && apt-get install -y python3-dev libpq-dev gcc

RUN pip install --upgrade pip
COPY requirements/base.txt .
COPY requirements/prod.txt .
RUN pip install -r prod.txt

COPY . .