FROM python:3.9.9-slim

WORKDIR /usr/src/educa

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y python3-dev libpq-dev gcc

RUN pip install --upgrade pip
COPY requirements/base.txt .
COPY requirements/dev.txt .
RUN pip install -r dev.txt

COPY . .