# Generated by Django 3.1.13 on 2021-10-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_instructor',
            field=models.BooleanField(default=False, help_text='Select this iff you want to be an instructor', verbose_name='are you a instructor'),
        ),
    ]
