# Generated by Django 3.1.13 on 2021-10-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_instructor',
            field=models.BooleanField(default=False, help_text='Select this if you want to be an instructor', verbose_name='are you a instructor'),
        ),
    ]
